# Generated by Django 5.1.7 on 2025-03-16 10:10

import ReposManager.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_name', models.CharField(max_length=50)),
                ('pkg_version', models.CharField(max_length=30)),
                ('pkg_description', models.CharField(max_length=1000)),
                ('pkg_publish_date', models.DateField()),
                ('pkg_file', models.FileField(upload_to=ReposManager.models.package_upload_path, validators=[ReposManager.models.validate_zip_file])),
                ('verification_status', models.CharField(choices=[('pending', 'На проверке'), ('verified', 'Проверен'), ('rejected', 'Отклонен')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pkg_publish_date', '-pkg_version'],
                'unique_together': {('pkg_name', 'pkg_version')},
            },
        ),
    ]
